/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CalendarEvent {
  'id' : bigint,
  'topic' : string,
  'dayOfWeek' : bigint,
  'completed' : boolean,
  'durationMinutes' : bigint,
  'subjectId' : bigint,
  'startHour' : bigint,
}
export type ConfidenceLabel = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface Goal {
  'id' : bigint,
  'targetScore' : bigint,
  'deadline' : Time,
  'subjectId' : bigint,
  'currentScore' : bigint,
}
export type Priority = { 'must_do' : null } |
  { 'should_do' : null } |
  { 'drop' : null };
export interface StudySession {
  'id' : bigint,
  'startTime' : Time,
  'focusRating' : bigint,
  'topic' : string,
  'endTime' : Time,
  'completed' : boolean,
  'durationMinutes' : bigint,
  'subjectId' : bigint,
}
export interface Subject {
  'id' : bigint,
  'revisionDueDate' : [] | [Time],
  'name' : string,
  'lastStudied' : Time,
  'confidenceLabel' : ConfidenceLabel,
  'strengthScore' : bigint,
  'timeInvested' : bigint,
  'priority' : Priority,
}
export type Time = bigint;
export interface UpdateEvent {
  'id' : bigint,
  'topic' : string,
  'dayOfWeek' : bigint,
  'completed' : boolean,
  'durationMinutes' : bigint,
  'subjectId' : bigint,
  'startHour' : bigint,
}
export interface UpdateGoal {
  'id' : bigint,
  'targetScore' : bigint,
  'deadline' : Time,
  'subjectId' : bigint,
  'currentScore' : bigint,
}
export interface UpdateSession {
  'id' : bigint,
  'startTime' : Time,
  'focusRating' : bigint,
  'topic' : string,
  'endTime' : Time,
  'completed' : boolean,
  'durationMinutes' : bigint,
  'subjectId' : bigint,
}
export interface UpdateSubject {
  'id' : bigint,
  'revisionDueDate' : [] | [Time],
  'name' : string,
  'lastStudied' : Time,
  'confidenceLabel' : ConfidenceLabel,
  'strengthScore' : bigint,
  'timeInvested' : bigint,
  'priority' : Priority,
}
export interface _SERVICE {
  'createCalendarEvent' : ActorMethod<
    [bigint, bigint, bigint, bigint, string],
    bigint
  >,
  'createGoal' : ActorMethod<[bigint, bigint, bigint, Time], bigint>,
  'createStudySession' : ActorMethod<
    [bigint, Time, Time, bigint, string],
    bigint
  >,
  'createSubject' : ActorMethod<[string], bigint>,
  'deleteCalendarEvent' : ActorMethod<[bigint], undefined>,
  'deleteGoal' : ActorMethod<[bigint], undefined>,
  'deleteStudySession' : ActorMethod<[bigint], undefined>,
  'deleteSubject' : ActorMethod<[bigint], undefined>,
  'getAllCalendarEvents' : ActorMethod<[], Array<CalendarEvent>>,
  'getAllGoals' : ActorMethod<[], Array<Goal>>,
  'getAllStudySessions' : ActorMethod<[], Array<StudySession>>,
  'getAllSubjects' : ActorMethod<[], Array<Subject>>,
  'getAvoidedSubjects' : ActorMethod<[], Array<Subject>>,
  'getCalendarEvent' : ActorMethod<[bigint], CalendarEvent>,
  'getGoal' : ActorMethod<[bigint], Goal>,
  'getRevisionDueSubjects' : ActorMethod<[], Array<Subject>>,
  'getStudySession' : ActorMethod<[bigint], StudySession>,
  'getSubject' : ActorMethod<[bigint], Subject>,
  'getSubjectsByPriority' : ActorMethod<[], Array<Subject>>,
  'updateCalendarEvent' : ActorMethod<[UpdateEvent], undefined>,
  'updateGoal' : ActorMethod<[UpdateGoal], undefined>,
  'updateStudySession' : ActorMethod<[UpdateSession], undefined>,
  'updateSubject' : ActorMethod<[UpdateSubject], undefined>,
  'updateSubjectLastStudied' : ActorMethod<[bigint, Time], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];