/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const CalendarEvent = IDL.Record({
  'id' : IDL.Nat,
  'topic' : IDL.Text,
  'dayOfWeek' : IDL.Nat,
  'completed' : IDL.Bool,
  'durationMinutes' : IDL.Nat,
  'subjectId' : IDL.Nat,
  'startHour' : IDL.Nat,
});
export const Goal = IDL.Record({
  'id' : IDL.Nat,
  'targetScore' : IDL.Nat,
  'deadline' : Time,
  'subjectId' : IDL.Nat,
  'currentScore' : IDL.Nat,
});
export const StudySession = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : Time,
  'focusRating' : IDL.Nat,
  'topic' : IDL.Text,
  'endTime' : Time,
  'completed' : IDL.Bool,
  'durationMinutes' : IDL.Nat,
  'subjectId' : IDL.Nat,
});
export const ConfidenceLabel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const Priority = IDL.Variant({
  'must_do' : IDL.Null,
  'should_do' : IDL.Null,
  'drop' : IDL.Null,
});
export const Subject = IDL.Record({
  'id' : IDL.Nat,
  'revisionDueDate' : IDL.Opt(Time),
  'name' : IDL.Text,
  'lastStudied' : Time,
  'confidenceLabel' : ConfidenceLabel,
  'strengthScore' : IDL.Nat,
  'timeInvested' : IDL.Nat,
  'priority' : Priority,
});
export const UpdateEvent = IDL.Record({
  'id' : IDL.Nat,
  'topic' : IDL.Text,
  'dayOfWeek' : IDL.Nat,
  'completed' : IDL.Bool,
  'durationMinutes' : IDL.Nat,
  'subjectId' : IDL.Nat,
  'startHour' : IDL.Nat,
});
export const UpdateGoal = IDL.Record({
  'id' : IDL.Nat,
  'targetScore' : IDL.Nat,
  'deadline' : Time,
  'subjectId' : IDL.Nat,
  'currentScore' : IDL.Nat,
});
export const UpdateSession = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : Time,
  'focusRating' : IDL.Nat,
  'topic' : IDL.Text,
  'endTime' : Time,
  'completed' : IDL.Bool,
  'durationMinutes' : IDL.Nat,
  'subjectId' : IDL.Nat,
});
export const UpdateSubject = IDL.Record({
  'id' : IDL.Nat,
  'revisionDueDate' : IDL.Opt(Time),
  'name' : IDL.Text,
  'lastStudied' : Time,
  'confidenceLabel' : ConfidenceLabel,
  'strengthScore' : IDL.Nat,
  'timeInvested' : IDL.Nat,
  'priority' : Priority,
});

export const idlService = IDL.Service({
  'createCalendarEvent' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createGoal' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, Time], [IDL.Nat], []),
  'createStudySession' : IDL.Func(
      [IDL.Nat, Time, Time, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createSubject' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'deleteCalendarEvent' : IDL.Func([IDL.Nat], [], []),
  'deleteGoal' : IDL.Func([IDL.Nat], [], []),
  'deleteStudySession' : IDL.Func([IDL.Nat], [], []),
  'deleteSubject' : IDL.Func([IDL.Nat], [], []),
  'getAllCalendarEvents' : IDL.Func([], [IDL.Vec(CalendarEvent)], ['query']),
  'getAllGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
  'getAllStudySessions' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
  'getAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getAvoidedSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getCalendarEvent' : IDL.Func([IDL.Nat], [CalendarEvent], ['query']),
  'getGoal' : IDL.Func([IDL.Nat], [Goal], ['query']),
  'getRevisionDueSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getStudySession' : IDL.Func([IDL.Nat], [StudySession], ['query']),
  'getSubject' : IDL.Func([IDL.Nat], [Subject], ['query']),
  'getSubjectsByPriority' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'updateCalendarEvent' : IDL.Func([UpdateEvent], [], []),
  'updateGoal' : IDL.Func([UpdateGoal], [], []),
  'updateStudySession' : IDL.Func([UpdateSession], [], []),
  'updateSubject' : IDL.Func([UpdateSubject], [], []),
  'updateSubjectLastStudied' : IDL.Func([IDL.Nat, Time], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const CalendarEvent = IDL.Record({
    'id' : IDL.Nat,
    'topic' : IDL.Text,
    'dayOfWeek' : IDL.Nat,
    'completed' : IDL.Bool,
    'durationMinutes' : IDL.Nat,
    'subjectId' : IDL.Nat,
    'startHour' : IDL.Nat,
  });
  const Goal = IDL.Record({
    'id' : IDL.Nat,
    'targetScore' : IDL.Nat,
    'deadline' : Time,
    'subjectId' : IDL.Nat,
    'currentScore' : IDL.Nat,
  });
  const StudySession = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : Time,
    'focusRating' : IDL.Nat,
    'topic' : IDL.Text,
    'endTime' : Time,
    'completed' : IDL.Bool,
    'durationMinutes' : IDL.Nat,
    'subjectId' : IDL.Nat,
  });
  const ConfidenceLabel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Priority = IDL.Variant({
    'must_do' : IDL.Null,
    'should_do' : IDL.Null,
    'drop' : IDL.Null,
  });
  const Subject = IDL.Record({
    'id' : IDL.Nat,
    'revisionDueDate' : IDL.Opt(Time),
    'name' : IDL.Text,
    'lastStudied' : Time,
    'confidenceLabel' : ConfidenceLabel,
    'strengthScore' : IDL.Nat,
    'timeInvested' : IDL.Nat,
    'priority' : Priority,
  });
  const UpdateEvent = IDL.Record({
    'id' : IDL.Nat,
    'topic' : IDL.Text,
    'dayOfWeek' : IDL.Nat,
    'completed' : IDL.Bool,
    'durationMinutes' : IDL.Nat,
    'subjectId' : IDL.Nat,
    'startHour' : IDL.Nat,
  });
  const UpdateGoal = IDL.Record({
    'id' : IDL.Nat,
    'targetScore' : IDL.Nat,
    'deadline' : Time,
    'subjectId' : IDL.Nat,
    'currentScore' : IDL.Nat,
  });
  const UpdateSession = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : Time,
    'focusRating' : IDL.Nat,
    'topic' : IDL.Text,
    'endTime' : Time,
    'completed' : IDL.Bool,
    'durationMinutes' : IDL.Nat,
    'subjectId' : IDL.Nat,
  });
  const UpdateSubject = IDL.Record({
    'id' : IDL.Nat,
    'revisionDueDate' : IDL.Opt(Time),
    'name' : IDL.Text,
    'lastStudied' : Time,
    'confidenceLabel' : ConfidenceLabel,
    'strengthScore' : IDL.Nat,
    'timeInvested' : IDL.Nat,
    'priority' : Priority,
  });
  
  return IDL.Service({
    'createCalendarEvent' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createGoal' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, Time], [IDL.Nat], []),
    'createStudySession' : IDL.Func(
        [IDL.Nat, Time, Time, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createSubject' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'deleteCalendarEvent' : IDL.Func([IDL.Nat], [], []),
    'deleteGoal' : IDL.Func([IDL.Nat], [], []),
    'deleteStudySession' : IDL.Func([IDL.Nat], [], []),
    'deleteSubject' : IDL.Func([IDL.Nat], [], []),
    'getAllCalendarEvents' : IDL.Func([], [IDL.Vec(CalendarEvent)], ['query']),
    'getAllGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
    'getAllStudySessions' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
    'getAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getAvoidedSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getCalendarEvent' : IDL.Func([IDL.Nat], [CalendarEvent], ['query']),
    'getGoal' : IDL.Func([IDL.Nat], [Goal], ['query']),
    'getRevisionDueSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getStudySession' : IDL.Func([IDL.Nat], [StudySession], ['query']),
    'getSubject' : IDL.Func([IDL.Nat], [Subject], ['query']),
    'getSubjectsByPriority' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'updateCalendarEvent' : IDL.Func([UpdateEvent], [], []),
    'updateGoal' : IDL.Func([UpdateGoal], [], []),
    'updateStudySession' : IDL.Func([UpdateSession], [], []),
    'updateSubject' : IDL.Func([UpdateSubject], [], []),
    'updateSubjectLastStudied' : IDL.Func([IDL.Nat, Time], [], []),
  });
};

export const init = ({ IDL }) => { return []; };