/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UpdateEvent {
    id: bigint;
    topic: string;
    dayOfWeek: bigint;
    completed: boolean;
    durationMinutes: bigint;
    subjectId: bigint;
    startHour: bigint;
}
export type Time = bigint;
export interface CalendarEvent {
    id: bigint;
    topic: string;
    dayOfWeek: bigint;
    completed: boolean;
    durationMinutes: bigint;
    subjectId: bigint;
    startHour: bigint;
}
export interface UpdateGoal {
    id: bigint;
    targetScore: bigint;
    deadline: Time;
    subjectId: bigint;
    currentScore: bigint;
}
export interface UpdateSession {
    id: bigint;
    startTime: Time;
    focusRating: bigint;
    topic: string;
    endTime: Time;
    completed: boolean;
    durationMinutes: bigint;
    subjectId: bigint;
}
export interface StudySession {
    id: bigint;
    startTime: Time;
    focusRating: bigint;
    topic: string;
    endTime: Time;
    completed: boolean;
    durationMinutes: bigint;
    subjectId: bigint;
}
export interface UpdateSubject {
    id: bigint;
    revisionDueDate?: Time;
    name: string;
    lastStudied: Time;
    confidenceLabel: ConfidenceLabel;
    strengthScore: bigint;
    timeInvested: bigint;
    priority: Priority;
}
export interface Subject {
    id: bigint;
    revisionDueDate?: Time;
    name: string;
    lastStudied: Time;
    confidenceLabel: ConfidenceLabel;
    strengthScore: bigint;
    timeInvested: bigint;
    priority: Priority;
}
export interface Goal {
    id: bigint;
    targetScore: bigint;
    deadline: Time;
    subjectId: bigint;
    currentScore: bigint;
}
export enum ConfidenceLabel {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum Priority {
    must_do = "must_do",
    should_do = "should_do",
    drop = "drop"
}
export interface backendInterface {
    createCalendarEvent(subjectId: bigint, dayOfWeek: bigint, startHour: bigint, durationMinutes: bigint, topic: string): Promise<bigint>;
    createGoal(subjectId: bigint, targetScore: bigint, currentScore: bigint, deadline: Time): Promise<bigint>;
    createStudySession(subjectId: bigint, startTime: Time, endTime: Time, focusRating: bigint, topic: string): Promise<bigint>;
    createSubject(name: string): Promise<bigint>;
    deleteCalendarEvent(id: bigint): Promise<void>;
    deleteGoal(id: bigint): Promise<void>;
    deleteStudySession(id: bigint): Promise<void>;
    deleteSubject(id: bigint): Promise<void>;
    getAllCalendarEvents(): Promise<Array<CalendarEvent>>;
    getAllGoals(): Promise<Array<Goal>>;
    getAllStudySessions(): Promise<Array<StudySession>>;
    getAllSubjects(): Promise<Array<Subject>>;
    getAvoidedSubjects(): Promise<Array<Subject>>;
    getCalendarEvent(id: bigint): Promise<CalendarEvent>;
    getGoal(id: bigint): Promise<Goal>;
    getRevisionDueSubjects(): Promise<Array<Subject>>;
    getStudySession(id: bigint): Promise<StudySession>;
    getSubject(id: bigint): Promise<Subject>;
    getSubjectsByPriority(): Promise<Array<Subject>>;
    updateCalendarEvent(input: UpdateEvent): Promise<void>;
    updateGoal(input: UpdateGoal): Promise<void>;
    updateStudySession(input: UpdateSession): Promise<void>;
    updateSubject(input: UpdateSubject): Promise<void>;
    updateSubjectLastStudied(subjectId: bigint, timestamp: Time): Promise<void>;
}
import type { ConfidenceLabel as _ConfidenceLabel, Priority as _Priority, Subject as _Subject, Time as _Time, UpdateSubject as _UpdateSubject } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createCalendarEvent(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCalendarEvent(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCalendarEvent(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createGoal(arg0: bigint, arg1: bigint, arg2: bigint, arg3: Time): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createGoal(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGoal(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createStudySession(arg0: bigint, arg1: Time, arg2: Time, arg3: bigint, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createStudySession(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStudySession(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createSubject(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createSubject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSubject(arg0);
            return result;
        }
    }
    async deleteCalendarEvent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCalendarEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCalendarEvent(arg0);
            return result;
        }
    }
    async deleteGoal(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGoal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGoal(arg0);
            return result;
        }
    }
    async deleteStudySession(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudySession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudySession(arg0);
            return result;
        }
    }
    async deleteSubject(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSubject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSubject(arg0);
            return result;
        }
    }
    async getAllCalendarEvents(): Promise<Array<CalendarEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCalendarEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCalendarEvents();
            return result;
        }
    }
    async getAllGoals(): Promise<Array<Goal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGoals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGoals();
            return result;
        }
    }
    async getAllStudySessions(): Promise<Array<StudySession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudySessions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudySessions();
            return result;
        }
    }
    async getAllSubjects(): Promise<Array<Subject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubjects();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubjects();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvoidedSubjects(): Promise<Array<Subject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvoidedSubjects();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvoidedSubjects();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCalendarEvent(arg0: bigint): Promise<CalendarEvent> {
        if (this.processError) {
            try {
                const result = await this.actor.getCalendarEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCalendarEvent(arg0);
            return result;
        }
    }
    async getGoal(arg0: bigint): Promise<Goal> {
        if (this.processError) {
            try {
                const result = await this.actor.getGoal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGoal(arg0);
            return result;
        }
    }
    async getRevisionDueSubjects(): Promise<Array<Subject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRevisionDueSubjects();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRevisionDueSubjects();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudySession(arg0: bigint): Promise<StudySession> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudySession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudySession(arg0);
            return result;
        }
    }
    async getSubject(arg0: bigint): Promise<Subject> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubject(arg0);
                return from_candid_Subject_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubject(arg0);
            return from_candid_Subject_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubjectsByPriority(): Promise<Array<Subject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubjectsByPriority();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubjectsByPriority();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCalendarEvent(arg0: UpdateEvent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCalendarEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCalendarEvent(arg0);
            return result;
        }
    }
    async updateGoal(arg0: UpdateGoal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGoal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGoal(arg0);
            return result;
        }
    }
    async updateStudySession(arg0: UpdateSession): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudySession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudySession(arg0);
            return result;
        }
    }
    async updateSubject(arg0: UpdateSubject): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubject(to_candid_UpdateSubject_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubject(to_candid_UpdateSubject_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateSubjectLastStudied(arg0: bigint, arg1: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubjectLastStudied(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubjectLastStudied(arg0, arg1);
            return result;
        }
    }
}
function from_candid_ConfidenceLabel_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConfidenceLabel): ConfidenceLabel {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Priority_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Priority): Priority {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Subject_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Subject): Subject {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    revisionDueDate: [] | [_Time];
    name: string;
    lastStudied: _Time;
    confidenceLabel: _ConfidenceLabel;
    strengthScore: bigint;
    timeInvested: bigint;
    priority: _Priority;
}): {
    id: bigint;
    revisionDueDate?: Time;
    name: string;
    lastStudied: Time;
    confidenceLabel: ConfidenceLabel;
    strengthScore: bigint;
    timeInvested: bigint;
    priority: Priority;
} {
    return {
        id: value.id,
        revisionDueDate: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.revisionDueDate)),
        name: value.name,
        lastStudied: value.lastStudied,
        confidenceLabel: from_candid_ConfidenceLabel_n5(_uploadFile, _downloadFile, value.confidenceLabel),
        strengthScore: value.strengthScore,
        timeInvested: value.timeInvested,
        priority: from_candid_Priority_n7(_uploadFile, _downloadFile, value.priority)
    };
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): ConfidenceLabel {
    return "low" in value ? ConfidenceLabel.low : "high" in value ? ConfidenceLabel.high : "medium" in value ? ConfidenceLabel.medium : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    must_do: null;
} | {
    should_do: null;
} | {
    drop: null;
}): Priority {
    return "must_do" in value ? Priority.must_do : "should_do" in value ? Priority.should_do : "drop" in value ? Priority.drop : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Subject>): Array<Subject> {
    return value.map((x)=>from_candid_Subject_n2(_uploadFile, _downloadFile, x));
}
function to_candid_ConfidenceLabel_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConfidenceLabel): _ConfidenceLabel {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Priority_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): _Priority {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateSubject_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateSubject): _UpdateSubject {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    revisionDueDate?: Time;
    name: string;
    lastStudied: Time;
    confidenceLabel: ConfidenceLabel;
    strengthScore: bigint;
    timeInvested: bigint;
    priority: Priority;
}): {
    id: bigint;
    revisionDueDate: [] | [_Time];
    name: string;
    lastStudied: _Time;
    confidenceLabel: _ConfidenceLabel;
    strengthScore: bigint;
    timeInvested: bigint;
    priority: _Priority;
} {
    return {
        id: value.id,
        revisionDueDate: value.revisionDueDate ? candid_some(value.revisionDueDate) : candid_none(),
        name: value.name,
        lastStudied: value.lastStudied,
        confidenceLabel: to_candid_ConfidenceLabel_n11(_uploadFile, _downloadFile, value.confidenceLabel),
        strengthScore: value.strengthScore,
        timeInvested: value.timeInvested,
        priority: to_candid_Priority_n13(_uploadFile, _downloadFile, value.priority)
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConfidenceLabel): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == ConfidenceLabel.low ? {
        low: null
    } : value == ConfidenceLabel.high ? {
        high: null
    } : value == ConfidenceLabel.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): {
    must_do: null;
} | {
    should_do: null;
} | {
    drop: null;
} {
    return value == Priority.must_do ? {
        must_do: null
    } : value == Priority.should_do ? {
        should_do: null
    } : value == Priority.drop ? {
        drop: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
